/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.*;

import java.util.HashSet;
import java.util.Random;
	
/**
 *
 * @author Ishan
 */
public class Exam extends javax.swing.JFrame {
   String F=""+StartPage.EMail+"";
String bt=""+CandidateAfterLogIn.B+"";
        String bb=""+CandidateAfterLogIn.BB+"";
        String bc=""+CandidateAfterLogIn.BC+"";
    int i;   
  int a[]=new int[50];
int za=0;
      
            
    int z=0;      
  int l;  
   int i1=1;
   int s=0;

   int c=0;
  
  
        String E=null;   
     
       
        
      

String R1,R2,R3,R4;
class CountDown extends Thread
{
	int min,sec;
	public void run()
	{
		for(min=29;min>=00;min--)
		{
			for(sec=59;sec>=00;sec--)
			{
				try
					{       
					//	System.out.println(min+" mm "+sec+" ss ");
						Exam.jLabel13.setText(min+"");
                                                Exam.jLabel15.setText(sec+"");
                                                Thread.sleep(1000);
					}
				catch(InterruptedException e)
					{
						e.printStackTrace();
					}
			}
		}
                
                        
                        jLabel5.setVisible(false);
                        jLabel8.setVisible(false);
                        jPanel1.setVisible(false);
                        jLabel10.setVisible(false);
                        jLabel11.setVisible(false);
                        jLabel12.setVisible(false);
                        jLabel13.setVisible(false);
                        jLabel15.setVisible(false);
                        jRadioButton5.setVisible(false);
                        jRadioButton6.setVisible(false);
                        jRadioButton7.setVisible(false);
                        jRadioButton8.setVisible(false);
                        jButton2.setVisible(false);
                        jButton3.setVisible(true);
                    
                        
                
		System.out.println("Time's Up!!!");
	}
	
		
}
    /**
     * Creates new form Exam
     */
    public Exam() 
    {
          
       initComponents();
       jButton1.setVisible(false);
       jLabel7.setVisible(false);
       jLabel10.setVisible(false);
       jLabel11.setVisible(false);
       jLabel12.setVisible(false);
       jPanel1.setVisible(false);
       jLabel5.setVisible(false);
       jLabel8.setVisible(false);
       jButton2.setVisible(true);
       jLabel6.setVisible(false);
       jRadioButton5.setVisible(false);
       jRadioButton6.setVisible(false);
       jRadioButton7.setVisible(false);
       jRadioButton8.setVisible(false);
       jLabel2.setText(F);
jButton3.setVisible(false);
       jLabel13.setVisible(false);
       jLabel15.setVisible(false);
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Dear");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 11, -1, 83));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("You will be given 30 mins. to answer 25 MCQ questions.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Each correct answer have 4 marks. All the best!!!");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, -1, -1));

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 660, -1, -1));

        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*Submit to get your Result");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 630, 253, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 430, 23));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Q");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 28, 44));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("P");
        jRadioButton5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton5StateChanged(evt);
            }
        });
        jRadioButton5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton5ItemStateChanged(evt);
            }
        });
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 424, 250, -1));

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("R");
        jRadioButton7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton7StateChanged(evt);
            }
        });
        jRadioButton7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton7ItemStateChanged(evt);
            }
        });
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 577, 250, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Q");
        jRadioButton6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton6StateChanged(evt);
            }
        });
        jRadioButton6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton6ItemStateChanged(evt);
            }
        });
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 424, 250, -1));

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("S");
        jRadioButton8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton8StateChanged(evt);
            }
        });
        jRadioButton8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton8ItemStateChanged(evt);
            }
        });
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 577, 250, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 43, 44));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 500, 62));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("Timer :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 153));
        jLabel11.setText("mm");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 30, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 153));
        jLabel12.setText("ss");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 20, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 30, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 30, 30));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 216, -1, -1));

        jButton1.setText("LogOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 118, -1, -1));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pen-and-paper.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jLabel2.setVisible(false);
        jButton4.setVisible(false);
        
        System.out.println(bt);
        System.out.println(bb);
        System.out.println(bc);
        jPanel1.setVisible(true);
       jLabel5.setVisible(true);
       jLabel8.setVisible(true);
       jRadioButton5.setVisible(true);
       jRadioButton6.setVisible(true);
       jRadioButton7.setVisible(true);
       jRadioButton8.setVisible(true);
       

String str=evt.getActionCommand();
if(str.equals("Start"))
{
        CountDown cd=new CountDown();
        System.out.println("Timer started...");
        cd.start();
    jLabel10.setVisible(true);
    jLabel11.setVisible(true);
    jLabel12.setVisible(true);
    jLabel13.setVisible(true);
    jLabel15.setVisible(true);
    
     Random rand = new Random();
           int m;
            int t;
            int g = 25;
            HashSet<Integer> randomNumbers = new HashSet<Integer>();
            for( t=0;t<=24;t++)
            {
                m = (rand.nextInt(35));
                if(m!=0)
                {
                if(!randomNumbers.contains(m))
                {
                randomNumbers.add(m);
                if (randomNumbers.size() <= 25) {
                    if (randomNumbers.size() == 25) {
                        g = 25;
                    }
                    g++;
                    randomNumbers.add(m);
                    System.out.println(m);
                    a[t]=m;
                }
                }
                else
                {
                    t--;
                }
                }
                else
                    t--;
            }
            jButton2.setLabel("Forward");
}
System.out.println();
System.out.println();
System.out.println(i);
if(str.equals("Forward"))
        {
           
            z=z+1;
        }
        
             
if(jRadioButton5.isSelected()&&R1.equals(E))
 {
     s=s+4;
 System.out.println("Congo:"+s);
                  }
           
           
           else if(jRadioButton6.isSelected()&&R2.equals(E))
           {
           
              s=s+4;
             System.out.println("Congo:"+s);
                  
              }
           
           
           else  if(jRadioButton7.isSelected()&&R3.equals(E))
           {
               
           
              s=s+4;
             System.out.println("Congo:"+s);
                  }
              
           
           
          else if(jRadioButton8.isSelected()&&R4.equals(E))
           {
           
              s=s+4;
             System.out.println("Congo:"+s);
                  }
          else 
              s=s+0;


        
        
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
 
        
        if (z==25)
        {
            jPanel1.setVisible(false);
       jLabel5.setVisible(false);
       jLabel8.setVisible(false);
            jRadioButton5.setVisible(false);
       jRadioButton6.setVisible(false);
       jRadioButton7.setVisible(false);
       jRadioButton8.setVisible(false);
                
                    jButton3.setVisible(true);
                    jButton2.setVisible(false);
            jLabel6.setVisible(true);
        }
        
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("first Step Completed\t"+"Driver Loaded");

            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","root");
            System.out.println("Second Step Completed\t"+"Connected");

            Statement st=con.createStatement();
            System.out.println("Third Step Completed\t"+"Statement Created\n\n");
            if(bt.equals("B.Tech"))
            {
            String sql="select Question,A,B,C,D,Answer from btechpaper where Sno='"+a[i++]+"'";

            ResultSet rs=st.executeQuery(sql);

            while(rs.next())
            {

                String a=""+i1;

                //int qno=Integer.parseInt(a);e
                String Q=rs.getString(1);
                String A=rs.getString(2);
                String B=rs.getString(3);
                String C=rs.getString(4);
                String D=rs.getString(5);
                 E=rs.getString(6);
                System.out.println("The value of E is"+E);
                

                jLabel8.setText(a);
                jTextArea1.setText(Q);
                jRadioButton5.setText(A);
                jRadioButton6.setText(B);
                jRadioButton7.setText(C);
                jRadioButton8.setText(D);
                i1++;

            }
            
            }
            else if(bb.equals("BBA"))
            {
                String sql="select Question,A,B,C,D,Answer from bbapaper where Sno='"+a[i++]+"'";

            ResultSet rs=st.executeQuery(sql);

            while(rs.next())
            {

                String a=""+i1;

                //int qno=Integer.parseInt(a);e
                String Q=rs.getString(1);
                String A=rs.getString(2);
                String B=rs.getString(3);
                String C=rs.getString(4);
                String D=rs.getString(5);
                 E=rs.getString(6);
                System.out.println("The value of E is"+E);
                

                jLabel8.setText(a);
                jTextArea1.setText(Q);
                jRadioButton5.setText(A);
                jRadioButton6.setText(B);
                jRadioButton7.setText(C);
                jRadioButton8.setText(D);
                i1++;

            }
            }
            else if(bc.equals("BCA"))
            {
                String sql="select Question,A,B,C,D,Answer from bcapaper where Sno='"+a[i++]+"'";

            ResultSet rs=st.executeQuery(sql);

            while(rs.next())
            {

                String a=""+i1;

                //int qno=Integer.parseInt(a);e
                String Q=rs.getString(1);
                String A=rs.getString(2);
                String B=rs.getString(3);
                String C=rs.getString(4);
                String D=rs.getString(5);
                 E=rs.getString(6);
                System.out.println("The value of E is"+E);
                

                jLabel8.setText(a);
                jTextArea1.setText(Q);
                jRadioButton5.setText(A);
                jRadioButton6.setText(B);
                jRadioButton7.setText(C);
                jRadioButton8.setText(D);
                i1++;

            }
            }
        
        }
        catch(ClassNotFoundException e)
        {
            System.out.println("Problem is 1\t"+e);

        }catch(SQLException e)
        {
            System.out.println("Problem is 2\t"+e.getMessage());
        }

           R1=jRadioButton5.getLabel();
           R2=jRadioButton6.getLabel();
           R3=jRadioButton7.getLabel();
           R4=jRadioButton8.getLabel();
           System.out.println("The R1 is "+R1);
           System.out.println("The R2 is "+R2);
           System.out.println("The R3 is "+R3);
           System.out.println("The R4 is "+R4);
           
        
        buttonGroup1.clearSelection();
         

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code her
      
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:   
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton6StateChanged
  
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButton6StateChanged

    private void jRadioButton5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton5ItemStateChanged
    
        
        // TODO add your handling codhere:
        
    }//GEN-LAST:event_jRadioButton5ItemStateChanged

    private void jRadioButton8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton8ItemStateChanged
       
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jRadioButton8ItemStateChanged

    private void jRadioButton7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton7ItemStateChanged
        
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jRadioButton7ItemStateChanged

    private void jRadioButton6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton6ItemStateChanged
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CountDown cd=new CountDown();
        cd.stop();
        jLabel6.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel15.setVisible(false);
        jButton1.setVisible(true);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("first Step Completed\t"+"Driver Loaded");

            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","root");
            System.out.println("Second Step Completed\t"+"Connected");

            Statement st=con.createStatement();
            System.out.println("Third Step Completed\t"+"Statement Created\n\n");

            
                System.out.print(bt);
                System.out.print(bb);
                System.out.print(bc);
            
                           if(bt.equals("B.Tech"))
                           {
                            
                            i=st.executeUpdate("insert into btresult(Name,Result) values('"+F+"','"+s+"')");       
                           }
                           else if(bb.equals("BBA"))
                           {
                               
                            i=st.executeUpdate("insert into bbresult(Name,Result) values('"+F+"','"+s+"')");
                           }
                           else if(bc.equals("BCA"))
                           {
                                
                            i=st.executeUpdate("insert into bcresult(Name,Result) values('"+F+"','"+s+"')");
                           }
            
        }
        catch(ClassNotFoundException e)
        {
            System.out.println("Problem is 1\t"+e);

        }catch(SQLException e)
        {
            System.out.println("Problem is 2\t"+e.getMessage());
        }
        System.out.print(F);
        
jLabel7.setVisible(true);
String b=null;
if(s<40)
{
b="Sorry!! Your score is "+s+" Not Qualified.";
}
else
    b="Congo: You are Qualified"+s;
jLabel7.setText(b);
        System.out.println(s);
        
jButton3.setVisible(false);        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton5StateChanged
     // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5StateChanged

    private void jRadioButton7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton7StateChanged
     // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7StateChanged

    private void jRadioButton8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton8StateChanged
       // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false);
new StartPage().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
setVisible(false);
        new CandidateAfterLogIn().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static  void main(String args[]) {
       
         
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam().setVisible(true);
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}

